version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_POSTGRES_USERNAME: myapplication
      SPRING_POSTGRES_PASSWORD: M3P@ssw0rd!
      SPRING_POSTGRES_URL: jdbc:postgresql://my-db-test.io:5432/mydatabase

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend